version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    reviewers:
      - "dzikrul1616"
    assignees:
      - "dzikrul1616"
