name: floating_logger
description: floating_logger is a Flutter library that provides a floating widget for real-time API request logs.

version: 0.0.2
homepage: https://github.com/dzikrul1616/flutter_floating_logger
repository: https://github.com/dzikrul1616/flutter_floating_logger
issue_tracker: https://github.com/dzikrul1616/flutter_floating_logger/issues

topics:
  - dio
  - logger 
  - floating

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.8.0+1
  equatable: ^2.0.7
  clipboard: ^0.1.3
  fluttertoast: ^8.2.10
  google_fonts: ^6.2.1 
  flutter:
    sdk: flutter
  flutter_styled_toast: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  mockito: ^5.4.4
  
 